# Generated by Django 4.1.3 on 2022-11-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='book',
        ),
    ]
