# Generated by Django 4.1.3 on 2022-12-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_sessions', '0004_booking_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]

    #         migrations.AddField(
    #         model_name='booking',
    #         name='date',
    #         field=models.DateField(default=''),
    #     ),
    #     migrations.AddField(
    #         model_name='booking',
    #         name='time',
    #         field=models.TimeField(default=''),
    #     ),
    # ]
