# Generated by Django 4.1.3 on 2023-01-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_sessions', '0009_booking_vaccination_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='VACC_YES',
            field=models.BooleanField(default=False),
        ),
    ]
