# Generated by Django 4.1.3 on 2023-01-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_sessions', '0010_booking_vacc_yes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='VACC_YES',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='Vaccination_Status',
        ),
    ]
