# Generated by Django 4.1.3 on 2023-01-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_sessions', '0011_remove_booking_vacc_yes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Vaccination_Status',
            field=models.CharField(choices=[('Y', 'Yes, my dog is vaccinated'), ('N', 'No, my dog is not vaccinated')], default='N', max_length=1),
        ),
    ]
