# Generated by Django 4.1.3 on 2023-01-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_sessions', '0012_booking_vaccination_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vaccinated_yes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
