# Generated by Django 4.1.3 on 2023-01-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_sessions', '0013_booking_vaccinated_yes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='vaccinated_yes',
        ),
    ]
