# Generated by Django 4.1.3 on 2022-11-29 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='home',
        ),
    ]
