# Generated by Django 4.1.3 on 2023-01-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
