# Generated by Django 4.1.3 on 2023-01-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccinated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VACC_CHOICES', models.CharField(choices=[('Y', 'Yes, my dog is vaccinated'), ('N', 'No, my dog is not vaccinated')], default='N', max_length=1)),
            ],
        ),
    ]
