# Generated by Django 4.1.3 on 2023-01-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_dogprofile_vaccinated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DogProfile',
        ),
        migrations.DeleteModel(
            name='Vaccinated',
        ),
    ]
